# Generated by Django 6.0.1 on 2026-02-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('content_rating', models.CharField(max_length=10)),
                ('is_switch_2', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
