# Generated by Django 6.0.1 on 2026-02-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameLibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='content_rating',
            field=models.CharField(max_length=5),
        ),
    ]
